### ISSUE TITLE
Why are the two unsafe blocks necessary in the code?

### ISSUE THREAD

**Issue by deckarep** [alexcrichton/socks5-rs#2]
I was hoping you could take a moment to explain why this proxy utilizes two unsafe blocks and if they're truly necessary?  I'd just like to understand if they're used for performance reasons or if it was completely required to fully implement a socks5 proxy.

I only ask for my own educational purposes and appreciate that you open sourced this.  Nice work!

**Comment by alexcrichton** [comment]
Better yet, I'll just remove it :)

This was because of a dependency on `bytes` which had unsafe functions, but that's no longer a dependency.
